### ISSUE TITLE
matplotlib 3.10: tests are failing

### ISSUE THREAD

**Issue by ahms5** [pyfar/pyfar#735] opened 2024-12-16 12:51 UTC
see https://app.circleci.com/jobs/github/pyfar/pyfar/13088

**Comment by f-brinkmann** [comment] 2024-12-17 10:45
3.10 is not stable yet and the part that fails contains a TODOs, which could solve the issue: https://github.com/matplotlib/matplotlib/blob/3ac0aea8be540028cb2510dabb43b290d15b503d/lib/matplotlib/artist.py#L258

I would suggest to restrict to Matplotlib<3.10 for now and keep this open until the issue is solved either in Matplotlib or in pyfar.

**Comment by f-brinkmann** [comment] 2024-12-17 10:59
Alternatively we could exchange https://github.com/pyfar/pyfar/blob/ecd0589a3fef83ec17e8d72a4bd5a3c64ef7c445/pyfar/plot/_interaction.py#L1114 for

```
# the behavior of text.remove() changed in Matplotlib 3.10. Even
# if the text exists, it can not always be removed. In these cases
# setting it to None is sufficient. Funnily, when it can be removed
# it still must be done.
try:
    self.txt.remove()
except Exception as _:
    pass
```

**Comment by ahms5** [comment] 2024-12-18 13:36
looks good to me, maybe be more explicit:

```
# the behavior of text.remove() changed in Matplotlib 3.10. Even
# if the text exists, it can not always be removed. In these cases
# setting it to None is sufficient. Funnily, when it can be removed
# it still must be done.
try:
    self.txt.remove()
except NotImplementedError as _:
    pass
```

**Comment by f-brinkmann** [comment] 2024-12-18 13:38
I'll draft a pull for discussion on Friday...

**Comment by mberz** [comment] 2024-12-18 17:12
Do you know if there's a related issue on www.github.com/matplotlib/matplotlib we could reference and track until the issue is fixed in matplotlib?

**Comment by ahms5** [comment] 2024-12-18 20:56
another issue is that matplotlib 3.10 is installed by default, even it is not released yet, its still an an unstable development version. maybe the problem is not matplotlib but our testing

**Comment by f-brinkmann** [comment] 2024-12-19 10:23
- I did not find an issue at Matplotlib (and was to lazy to make one) 
- I checked and found out that `pip install matplitlib` installs 3.10. I think Ii is rather a problem of Matplotlib not flagging it as a pre-release

**Comment by ahms5** [comment] 2024-12-19 10:34
yes, i think so too.

**Closed** 2024-12-19 10:40 UTC
